# Generated by Django 3.0.2 on 2020-01-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=64)),
                ('fullname', models.CharField(max_length=512)),
                ('gender', models.CharField(max_length=512)),
                ('college', models.CharField(max_length=512)),
                ('collegeaddress', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=512)),
                ('contact', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=512)),
                ('groupmembers', models.CharField(max_length=4000)),
            ],
        ),
    ]
