# Generated by Django 3.0.2 on 2020-01-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200118_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrevent',
            name='enablepayment',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
